name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Compile the TypeScript
        uses: icrawl/action-tsc@v1

      - name: Run the binary
        run: |
          node ./bin/lib.js
