name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Compile the TypeScript
        run: yarn install && yarn ts-node ./src/index.ts
      - name: Run the tests
        run: yarn run test
